### ISSUE TITLE
Unable to get keys

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [dojafoja/FunKii-UI#3]
![error](https://cloud.githubusercontent.com/assets/10351221/23323917/800f05d2-fab0-11e6-8bd9-a72ad38166f0.PNG)

**Comment by P3rf3ctXZer0** [comment]
I can still manually input the keys.

**Comment by dojafoja** [comment]
This is more an issue of the wiiu key site's auto-generated json file not working. It just 'goes down'  from time to time. Simply wait a few minutes and try again and it should work again. I plan on adding a pop up notification to tell the user about it and to try again shortly. Its more of an issue if it happens on first run since there is no local titlekeys.json to fall back on. If a local titlekeys.json is found it should still work but it will be missing any new titles and/or keys that may have been added since the last time the program was run.

**Comment by P3rf3ctXZer0** [comment]
How would I quickly get a title list manually? I just tried a few seconds ago and its still failing.

**Comment by dojafoja** [comment]
If it is still failing constantly, there may be another issue happening. There were two other users a while back who couldn't get it to work. It turned out to be a SSL certificate issue. Some time this morning I will send you a modified version that will disable SSL verification as well as printing the Exception type that happens. The key site is usually only 'down' for 10-15 minutes tops, so it makes me suspect something else is happening. Both of the previous users were able to get this type of error sorted using the files I will be sending you. I'm pretty confident that I can figure it out. As far as getting the file manually, try navigating on your pc to https://wiiu.title****.com/json. If your pc will connect to it then you can either download it or copy/paste it to a file named titlekeys.json. If your pc will not connect to the json then the site isn't working or something is blocking the connection. Give me an hour or less and I will send you files to try.

**Comment by P3rf3ctXZer0** [comment]
Yeah it worked to manually get the json file.

**Comment by XtraSmiley** [comment]
Hey, so the old site for keys, wiiu.title****.com is down, now it's .gq and I tired that but the GUI won't take that or .gq/json either. I tired typing that into the config screen as well and still when the terminal box pops up and says type here it won't take it with or without the http, so I'm not sure how to get this to run. Thanks!

**Comment by superarts** [comment]
@XtraSmiley I see the author fixed this issue in a recent build. Purge your `config.json` and enter the right site URL, and I think you need to add `http://` this time - previously it was hard-coded in the script, but the new site does not support `https` so I guess the author doesn't want to hard-code that bit anymore.

**Comment by dojafoja** [comment]
@superarts I actually only updated the command line portion of FunKiiU. This GUI has not been updated to work with it yet. This coming weekend I will push working files that will update this GUI to accept any url for the key site as well as some other new features.
