### ISSUE TITLE
 do_open raise URLError(err)

### ISSUE THREAD

**Issue by SpanishNewbie** [dojafoja/FunKii-UI#9]
I installed Phyton v 2.7 and then I downloaded Funkii-UI. The first time I clicked on Gui, it created a new FunkiiU and AutoComplete files (.pyc). However, it doesn't matter how many times I click on Gui, FunkiiU.py or FunkiiU.pyc, nothing changes. When I click on Gui, it always shows this:

> File "C:\Python27\lib|urlib2.py", line 1148, in do_open raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ss1.c:499: error:1407742E_SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> 

![error funkiiu](https://user-images.githubusercontent.com/40306131/41489240-8e9b651c-70ef-11e8-936b-84c31789430b.png)

**Comment by dojafoja** [comment]
Its because of Github deprecating older TLS versions. I have heard that upgrading to Python 3.6.x will fix the issue, I think they updated urllib2. If that doesn't work or isn't an option then you can use this version that I modified to not crash if checking for updates fails: http://www.mediafire.com/file/051ovq1qqd1n2ea/gui.py the only difference is that instead of crashing, it just sets the latest version number to 2.1.7.

**Comment by SpanishNewbie** [comment]
Thank you. I downloaded Python 3.6.0 and it worked.
